# -*- coding: utf-8 -*-
"""lab 2 REp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOctesMC4i5clTszl1hZflanv3JKlt3q

# lab 2 REp

# my name print
"""

print("my name is muhhamd hussain")

print("Hussain")

"""# Arithmatics"""

num = 2
num2 = 3
print(num + num2)

import numpy as np
num = 56
num1 = 56
print(num / num1)

num = int(input("enter the number: "))
num2 = int(input("enter the number: "))
print(num + num2)

"""# List"""

num =[1,2,3,4,5,6,7,8,9,10]
print("Orignal list",num)
print("sum: ",sum(num))
print("max",max(num))
print("min",min(num))
num.append(11)
num.remove(2)

print("Update List",num)

"""# while loop"""

num = 1
while num <= 5: # Corrected the loop condition to count down from 5 to 1
  print(num)
  num += 1
True

"""# Tuples

# list string fruits
"""

fruits = ("apple", "banana", "cherry","mango","graps")
print("second elements",fruits[1])
print("last element: ",fruits[-1])

fruit_list = list(fruits)
fruit_list[1] = "bukhary"
fruits = tuple(fruit_list)
print(fruits)

"""# Sets"""

num_2 = {1,2,3,4,5,6}
num_3={7,8,9}
print(num_2.union(num_3))
print(num_2.intersection(num_3))
print(num_2.difference(num_3))

"""# Dictionary"""

student = {"Ali": 85, "Ahmad": 89, "hussain": 67, "abid": 90}
print("keys:", student.keys())
print("values:", student.values())

#update value
student["Ali"] = 93
print("Update Dictionary: ", student)

#delete a key values pair
del student["Ahmad"]
print("After Deletion: ", student)